// src/pages/About.tsx
import { motion } from "framer-motion";
import { Link } from "react-router-dom";

export default function About() {
  return (
    <div className="h-screen w-screen flex items-center justify-center bg-gradient-to-br from-black via-gray-900 to-gray-800 text-white px-6 py-12">
      <motion.div
        className="max-w-3xl text-center"
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
      >
        <h2 className="text-4xl md:text-5xl font-bold mb-6 bg-gradient-to-r from-blue-400 to-cyan-300 text-transparent bg-clip-text">
          About betterfetch
        </h2>
        <p className="text-lg md:text-xl text-gray-300 leading-relaxed">
          <strong>betterfetch</strong> is a sleek, minimalist system info tool for the terminal, inspired by projects like <code>neofetch</code> and <code>pfetch</code>, but designed with simplicity and speed in mind.
          <br /><br />
          Whether you're customizing your terminal setup or just want a quick look at your system specs, betterfetch provides just the essentials — clean, readable, and fast.
        </p>
        <div className="mt-8">
          <Link
            to="https://github.com/betterfetch/betterfetch"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block px-6 py-3 bg-blue-600 text-white rounded-xl shadow-md hover:bg-blue-700 transition"
          >
            View on GitHub
          </Link>
        </div>
      </motion.div>
    </div>
  );
}

// src/pages/About.svelte
<script lang="ts">
</script>

<div class="max-w-3xl mx-auto">
  <h1 class="text-4xl md:text-5xl font-bold tracking-tight text-zinc-100 text-center">
    About betterfetch
  </h1>

  <div class="mt-8 space-y-6 text-zinc-300 leading-relaxed">
    <p>
      <strong class="text-cyan-400">betterfetch</strong> is a sleek, minimalist
      system info tool for the terminal, inspired by projects like
      <code class="text-zinc-100 bg-zinc-800 px-1.5 py-0.5 rounded text-sm">neofetch</code>
      and
      <code class="text-zinc-100 bg-zinc-800 px-1.5 py-0.5 rounded text-sm">pfetch</code>,
      but designed with simplicity and speed in mind.
    </p>
    <p>
      Whether you're customizing your terminal setup or just want a quick look
      at your system specs, betterfetch provides just the essentials: clean,
      readable, and lightning fast.
    </p>
  </div>

  <div class="mt-10 grid gap-4 md:grid-cols-3">
    <div class="rounded-lg border border-zinc-800 bg-zinc-900 p-5">
      <h3 class="font-semibold text-cyan-400 mb-2">Lightning Fast</h3>
      <p class="text-sm text-zinc-400">
        Executes in milliseconds. No bloat, no unnecessary dependencies.
      </p>
    </div>
    <div class="rounded-lg border border-zinc-800 bg-zinc-900 p-5">
      <h3 class="font-semibold text-cyan-400 mb-2">Minimal Design</h3>
      <p class="text-sm text-zinc-400">
        Clean output with just the essentials. Easy to read at a glance.
      </p>
    </div>
    <div class="rounded-lg border border-zinc-800 bg-zinc-900 p-5">
      <h3 class="font-semibold text-cyan-400 mb-2">Open Source</h3>
      <p class="text-sm text-zinc-400">
        GPLv3 licensed. Contribute on GitHub and help make it better.
      </p>
    </div>
  </div>

  <div class="mt-10 text-center">
    <a
      href="https://github.com/betterfetch/betterfetch"
      target="_blank"
      rel="noopener noreferrer"
      class="inline-flex items-center gap-2 px-8 py-3 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 font-medium rounded-lg transition-colors border border-zinc-700"
    >
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
        <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
      </svg>
      View on GitHub
    </a>
  </div>
</div>
