// src/pages/Download.tsx
import { motion } from "framer-motion";

export default function Download() {
  return (
    <div className="h-screen w-screen flex items-center justify-center bg-gradient-to-br from-gray-900 via-black to-gray-800 text-white px-6 py-12">
      <motion.div
        className="max-w-xl text-center"
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
      >
        <h2 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-blue-400 to-cyan-300 text-transparent bg-clip-text">
          Get betterfetch
        </h2>
        <p className="text-lg md:text-xl text-gray-300 mb-8">
          Download the latest version of <strong>betterfetch</strong> and instantly upgrade your terminal aesthetic.
          It's fast, minimal, and open source.
        </p>

        <a
          href="https://github.com/betterfetch/betterfetch"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block bg-blue-600 hover:bg-blue-700 transition px-8 py-3 text-lg rounded-xl font-medium shadow-lg"
        >
          Download from GitHub
        </a>

        <div className="mt-6 text-sm text-gray-500">
          Compatible with Linux & WSL. Requires a POSIX-compliant shell.
        </div>
      </motion.div>
    </div>
  );
}

// src/pages/Download.svelte
<script lang="ts">
</script>

<div class="max-w-2xl mx-auto">
  <h1 class="text-4xl md:text-5xl font-bold tracking-tight text-zinc-100 text-center">
    Get betterfetch
  </h1>

  <p class="mt-4 text-lg text-zinc-400 text-center">
    Download the latest version and upgrade your terminal aesthetic. It's fast,
    minimal, and open source.
  </p>

  <div class="mt-10 rounded-lg border border-zinc-800 bg-zinc-950 overflow-hidden">
    <div class="flex items-center gap-2 px-4 py-2.5 bg-zinc-900 border-b border-zinc-800">
      <div class="w-3 h-3 rounded-full bg-red-500/60"></div>
      <div class="w-3 h-3 rounded-full bg-yellow-500/60"></div>
      <div class="w-3 h-3 rounded-full bg-green-500/60"></div>
      <span class="ml-2 text-xs text-zinc-600">quick install</span>
    </div>
    <pre class="p-4 md:p-6 text-sm leading-relaxed font-mono text-zinc-300 overflow-x-auto"><code><span class="text-green-400">$</span> curl -fsSL https://betterfetch.github.io/scripts/rs/install.sh | bash</code></pre>
  </div>

  <div class="mt-8 text-center">
    <a
      href="https://github.com/betterfetch/betterfetch"
      target="_blank"
      rel="noopener noreferrer"
      class="inline-flex items-center gap-2 px-8 py-3 bg-cyan-500 hover:bg-cyan-400 text-zinc-950 font-semibold rounded-lg transition-colors"
    >
      Download from GitHub
      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
      </svg>
    </a>
  </div>

  <div class="mt-8 rounded-lg border border-zinc-800 bg-zinc-900 p-5">
    <h3 class="font-semibold text-zinc-100 mb-3">Requirements</h3>
    <ul class="text-sm text-zinc-400 space-y-2">
      <li class="flex items-center gap-2">
        <span class="text-green-400 shrink-0">•</span>
        Linux or WSL
      </li>
      <li class="flex items-center gap-2">
        <span class="text-green-400 shrink-0">•</span>
        POSIX-compliant shell (bash, zsh, etc.)
      </li>
      <li class="flex items-center gap-2">
        <span class="text-green-400 shrink-0">•</span>
        curl or wget for installation
      </li>
    </ul>
  </div>
</div>
